modLoader="javafml"
loaderVersion="[41,)"
license="GNU General Public License v3+"
issueTrackerURL="https://github.com/ItzSwirlz/CloneHeroMusicDiscs/issues/"

[[mods]]
modId="cloneheromusicdiscs"
version="${file.jarVersion}"
displayName="Clone Hero Music Discs"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/ItzSwirlz/CloneHeroMusicDiscs/"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #optional
credits="All the composers!"
authors="Joshua Peisach (ItzSwirlz)"
description='''
This mod takes famous songs in Clone Hero and creates music discs for them!

There are no added creative mode tabs or extra features - just the music discs,
and they are made to blend exactly with the game (other than a /give command because
of the modid the items are registered with). That includes creepers dropping these
custom music discs!

These songs were all added with consent of the original composer.

Visit the GitHub page to suggest a new song.
'''

[[dependencies.cloneheromusicdiscs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
